config/routes.rb
Rails.application.routes.draw do
  resources :preorders
  get 'pages/dashboard'
  resources :colors
  resources :customers
  resources :products
  resources :pages
  #get 'home/index'

  get 'home/About_us'
  get 'home/index'
  get 'home/colors'
  get 'home/pages'

    resources :pages, only: [:index]
    # or, if using the index as the homepage
    root 'pages#dashboard'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/color.rb
class Color < ApplicationRecord
  has_one_attached :image_color

  validates :name_color, presence: true
  validates :code_color, presence: true
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  before_action :set_color, only: %i[ show edit update destroy ]

  # GET /colors or /colors.json
  def index
    @colors = Color.all
  end

  # GET /colors/1 or /colors/1.json
  def show
    @color = Color.find(params[:id])
  end

  # GET /colors/new
  def new
    @color = Color.new
  end

  # GET /colors/1/edit
  def edit
  end

  # POST /colors or /colors.json
  def create
    @color = Color.new(color_params)

    respond_to do |format|
      if @color.save
        format.html { redirect_to color_url(@color), notice: "Color was successfully created." }
        format.json { render :show, status: :created, location: @color }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colors/1 or /colors/1.json
  def update
    respond_to do |format|
      if @color.update(color_params)
        format.html { redirect_to color_url(@color), notice: "Color was successfully updated." }
        format.json { render :show, status: :ok, location: @color }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colors/1 or /colors/1.json
  def destroy
    @color.destroy!

    respond_to do |format|
      format.html { redirect_to colors_url, notice: "Color was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_color
      @color = Color.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def color_params
      params.require(:color).permit(:image_color, :name_color, :code_color)
    end

  
    

end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/views/colors/_color.html.erb
<div id="<%= dom_id color %>">

  <p>
    <strong>Name color:</strong>
    <%= color.name_color %>
  </p>

  <p>
    <strong>Code color:</strong>
    <%= color.code_color %>
  </p>

</div>

app/views/colors/_form.html.erb
<%= form_with(model: color, local: true, html: { multipart: true }) do |form| %>
  <% if color.errors.any? %>
    <div id="error-messages">
      <h2 id="error-heading"><%= pluralize(color.errors.count, "error") %> prohibited this color from being saved:</h2>

      <ul id="error-list">
        <% color.errors.each do |error| %>
          <li id="error-item"><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div id="color-form-group">
    <label for="color_image" id="color_image_label">Select Color Image:</label>
    <%= form.file_field :image_color, id: "color_image" %>
  </div>

  <div id="color-form-group">
    <label for="color_name" id="color_name_label">Color Name:</label>
    <%= form.text_field :name_color, id: "color_name" %>
  </div>

  <div id="color-form-group">
    <label for="color_code" id="color_code_label">Color Code:</label>
    <%= form.text_field :code_color, id: "color_code" %>

  </div>

  <div>
    <%= form.submit "Save Color", id: "submit-button" %>
  </div>
<% end %>

app/views/colors/edit.html.erb
<h1 class="editing-color-header">Editing color</h1>

<%= render "form", color: @color %>

<br>

<div class="editing-color-actions">
  <a class="btn btn-primary" href="/colors/2/edit">Edit </a>
  <a class="btn btn-secondary" href="/colors">Back to colors</a>
</div>

app/views/colors/index.html.erb
<!-- NAV BAR -->  
    <nav class="navbar navbar-expand-lg" style="background-color: #da6220;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
    TjStockOptima</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="colors">Colors</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="customers">Customers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="products">Products</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
<p class="alert alert-success"><%= notice %></p>

<h1 class = "producttitle">Colors</h1>
<%= link_to "New color", new_color_path, class: "btn btn-success", id: "newcolor_btn"%>
<div id="colors" class="container">
  <div class="row">
    <% @colors.each do |color| %>
      <div class="col-md-4 color-item card mb-4 shadow-sm">
        <div class="card-body">
          <% if color.image_color.attached? %>
            <%= image_tag color.image_color, class: "card-img-top" %>
          <% else %>
            <p class="text-muted">No image uploaded.</p>
          <% end %>
          <div class="card-text">
            <%= render color %>
          </div>
          <p class="mt-3">
            <%= link_to "Show this color", color, class: "btn btn-primary" %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/colors/new.html.erb
<h1>New color</h1>

<%= render "form", color: @color %>

<br>

<div>
  <%= link_to "Back to colors", colors_path %>
</div>

app/views/colors/show.html.erb
<p style="color: green"><%= notice %></p>

<div id="colors" class="container">
  <div class="row">
    <div class="col-md-4 color-item card mb-4 shadow-sm">
        <div class="card-body">
          <%= image_tag @color.image_color, class: "card-img-top" %>
          <div class="card-text">
          <%= render @color %>
          </div>
        </div>
    </div>
  </div>
</div>
<p class="mt-3">
  <%= link_to "Edit ", edit_color_path(@color),class: "btn btn-primary" %> 
  <%= link_to "Back to colors", colors_path %>
  <%= button_to "Delete", @color, method: :delete, class: "btn btn-danger" %>
</p>  