config/routes.rb
Rails.application.routes.draw do
  resources :preorders
  get 'pages/dashboard'
  resources :colors
  resources :customers
  resources :products
  resources :pages
  #get 'home/index'

  get 'home/About_us'
  get 'home/index'
  get 'home/colors'
  get 'home/pages'

    resources :pages, only: [:index]
    # or, if using the index as the homepage
    root 'pages#dashboard'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/preorder.rb
class Preorder < ApplicationRecord
end

app/controllers/preorders_controller.rb
class PreordersController < ApplicationController
  before_action :set_preorder, only: %i[ show edit update destroy ]

  # GET /preorders or /preorders.json
  def index
    @preorders = Preorder.all
  end

  # GET /preorders/1 or /preorders/1.json
  def show
  end

  # GET /preorders/new
  def new
    @preorder = Preorder.new
  end

  # GET /preorders/1/edit
  def edit
  end

  # POST /preorders or /preorders.json
  def create
    @preorder = Preorder.new(preorder_params)

    respond_to do |format|
      if @preorder.save
        format.html { redirect_to preorder_url(@preorder), notice: "Preorder was successfully created." }
        format.json { render :show, status: :created, location: @preorder }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @preorder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /preorders/1 or /preorders/1.json
  def update
    respond_to do |format|
      if @preorder.update(preorder_params)
        format.html { redirect_to preorder_url(@preorder), notice: "Preorder was successfully updated." }
        format.json { render :show, status: :ok, location: @preorder }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @preorder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preorders/1 or /preorders/1.json
  def destroy
    @preorder.destroy!

    respond_to do |format|
      format.html { redirect_to preorders_url, notice: "Preorder was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preorder
      @preorder = Preorder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def preorder_params
      params.require(:preorder).permit(:color, :target_date, :quantity)
    end
end

app/helpers/preorders_helper.rb
module PreordersHelper
end

app/views/preorders/_form.html.erb
<%= form_with(model: preorder) do |form| %>
  <% if preorder.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(preorder.errors.count, "error") %> prohibited this preorder from being saved:</h2>

      <ul>
        <% preorder.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :color, style: "display: block" %>
    <%= form.text_field :color %>
  </div>

  <div>
    <%= form.label :target_date, style: "display: block" %>
    <%= form.date_field :target_date %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/preorders/_preorder.html.erb
<div id="<%= dom_id preorder %>">
  <p>
    <strong>Color:</strong>
    <%= preorder.color %>
  </p>

  <p>
    <strong>Target date:</strong>
    <%= preorder.target_date %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= preorder.quantity %>
  </p>

</div>

app/views/preorders/edit.html.erb
<h1>Editing preorder</h1>

<%= render "form", preorder: @preorder %>

<br>

<div>
  <%= link_to "Show this preorder", @preorder %> |
  <%= link_to "Back to preorders", preorders_path %>
</div>

app/views/preorders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Preorders</h1>

<div id="preorders">
  <% @preorders.each do |preorder| %>
    <%= render preorder %>
    <p>
      <%= link_to "Show this preorder", preorder %>
    </p>
  <% end %>
</div>

<%= link_to "New preorder", new_preorder_path %>

app/views/preorders/new.html.erb
<h1>New preorder</h1>

<%= render "form", preorder: @preorder %>

<br>

<div>
  <%= link_to "Back to preorders", preorders_path %>
</div>

app/views/preorders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @preorder %>

<div>
  <%= link_to "Edit this preorder", edit_preorder_path(@preorder) %> |
  <%= link_to "Back to preorders", preorders_path %>

  <%= button_to "Destroy this preorder", @preorder, method: :delete %>
</div>